### ISSUE TITLE
En tant que utlisateur connecté, je veux pouvoir filtrer les résultats en fonction de mes recherches

### ISSUE THREAD

**Issue by justinehell** [WildCodeSchool/Lyon-js-202005-project-shakeit#20]
- [x] Filter design : create search bar + add button + title "Search" @Myst3k69 

- [x] Filter function - ingredient : dynamically add the input (=ingredient) below the search bar (=tag) @Tradou 

- [x] Filter function - recipe : dynamically change the recipe card (=photo + name) depending on the ingredient added by the user  @Tradou @MarineMontailler 

- [x] Autocompletion : Allow user to see what tag is possible to search @Tradou 

                                             IMPROVEMENTS:
- [x] Autocompletion :  Take ingredient in a file from the API ( in case if new ingredient )

                                             MAYBE :
Limit tag?

**Comment by ghost** [comment]
Add functionnality that permit to user to see which tag has been typed. 
Add a files named lliste_ingredient that contains all the ingredient use in the API . 
WIP : need to improve autocompletion.

**Comment by ghost** [comment]
Change the aspect of the search bar. Now searchbar allow to users to see which tag is on search in the searchbar. User is able to cancel a tag. ( currenlty user is not able to type a non existing tag or to enter an empty tag )
