### ISSUE TITLE
you should regard useEffect for avoid class component

### ISSUE THREAD

**Issue by bugsfunny** [WildCodeSchool/Lyon-js-202005-project-shakeit#34]
https://github.com/WildCodeSchool/Lyon-js-202005-project-shakeit/blob/f6991a0b5c09c5955fc15b47c6b549fd726f9d9a/src/containers/RecipePage.js#L4

**Comment by MarineMontailler** [comment]
We'll do the change from "class" to "function" component, in a next sprint
